name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test
      run: go test -v -timeout 5m ./...
  
  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up benchstat
      run: go install golang.org/x/perf/cmd/...@latest

    - name: Benchmark
      run: go test -bench=. -count=10 -benchtime=1000x -run=^a ./... > bench.txt
      
    - name: Show results
      run: benchstat bench.txt
